# Generated by Django 4.0 on 2021-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('chrom', models.CharField(max_length=100)),
                ('pos', models.PositiveIntegerField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
