# Generated by Django 4.0 on 2022-01-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcfrow',
            name='my_pk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
